version: '0.2'
ignorePaths: ['git/*']
dictionaryDefinitions: []
dictionaries: []
words: [
    # ===== Dev ===== #
    'blockquotes',
    'bluegreen',
    'cheatsheet',
    'chrono',
    'codepen',
    'codesandbox',
    'cmark',
    'cpus',
    'cursorrules',
    'disqus',
    'dribbble',
    'evenodd',
    'favicons',
    'flyctl',
    'frontmatter',
    'gantt',
    'giscus',
    'haspopup',
    'headlessui',
    'icondata',
    'lastmod',
    'linecap',
    'linejoin',
    'lucide',
    'mathbf',
    'noopener',
    'noreferrer',
    'oklch',
    'opengraph',
    'pilcrow',
    'prerender',
    'println',
    'reflog',
    'rehype',
    'squircle',
    'strikethrough',
    'stylesheet',
    'tailwindlabs',
    'tasklists',
    'ungroup',
    'unparse',
    'worktree',
    'worktrees',
    # ===== Rust ===== #
    'askama',
    'binop',
    'bindgen',
    'binstall',
    'bmdavis419',
    'codegen',
    'cdylib',
    'clippy',
    'datelike',
    'dioxus',
    'expl',
    'itertools',
    'leptos',
    'leptosfmt',
    'msrv',
    'msvc',
    'prettyplease',
    'rlib',
    'rustc',
    'rustflags',
    'rustlang',
    'rustup',
    'serde',
    'thiserror',
    'walkdir',
    # ===== Username ===== #
    'dande',
    'dandedotdev',
    'itehax',
    'pocock',
    'superfly',
    'timlrx',
  ]
ignoreWords: []
import: []
